stages:
    - build

build-module:
    stage: build
    tags:
        - docker
    image: registry.gitlab.com/picodata/dockers/brod-builder:0.1
    script:
        - cd /builds/picodata/brod
        - cmake .
        - make
        - make install
